# Generated by Django 2.2.7 on 2019-11-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_position',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_you',
            field=models.TextField(blank=True, default='Информация обо мне...'),
        ),
    ]
