# Generated by Django 2.2.7 on 2019-11-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_role', '0001_initial'),
        ('crm', '0002_auto_20191109_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_role.Role'),
        ),
    ]
