# Generated by Django 2.2.7 on 2019-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_you',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
