# Generated by Django 2.2.7 on 2019-11-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_coordinate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
