# Generated by Django 2.2.7 on 2019-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_role', '0001_initial'),
        ('crm', '0006_coordinate_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='drf_role.Role'),
        ),
    ]
