# Generated by Django 2.2.7 on 2019-11-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20191110_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Не подтвержден', max_length=255),
        ),
    ]
